# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
    #using major version aliases
    # @link: (example) https://github.com/afragen/github-updater/blob/develop/.travis.yml
    - 5.4
    - 5.6
    - 7.0
    - hhvm
    
# optionally specify a list of environments, for example to test different RDBMS
# @link: https://github.com/travis-ci-examples/php/blob/master/.travis.yml
env:
    - DB=mysql

# optionally set up exclusions and allowed failures in the matrix
matrix:
    # exclude:
    allow_failures:
        - hhvm
    fast_finish: true

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev

# omitting "script:" will default to phpunit
script: phpunit
    
# configure notifications (email, IRC, campfire, etc)
notifications: 
    email:
        on_success: never
        on_failure: change